### ISSUE TITLE
pip install sqlalchemyplus

### ISSUE THREAD

**Issue by Lauriy** [opus-42/sqlalchemy-plus#1]
`pip install sqlalchemy-plus`

**Comment by opus-42** [comment]
Hello, Could you provide more detail about the issue you encounter ?

Please note that in order to install the package you need to run 

```bash 
pip install sqlalchemy-plus
```
And NOT
```bash 
pip install sqlalchemyplus
```

**Comment by Lauriy** [comment]
Yup, README needs a slight correction.

**Comment by opus-42** [comment]
Ok got it thanks

**Comment by opus-42** [comment]
I've juste updated the README following what you said. Thanks.
